name: mortgage_calculator
version: 0.0.1
author: Daniel Davidson <dbdavidson@yahoo.com>
dependencies:
  polymer: ">=0.15.0"
  logging: ">=0.9.2 <0.10.0"
  fixnum: ">=0.9.0"
  money:
      path: /Users/dbdavidson/dev/open_source/money

# custom <mortgage_calculator dependencies>
# end <mortgage_calculator dependencies>

dev_dependencies:
  unittest: ">=0.11.0"
  browser: "any"

# custom <mortgage_calculator dev dependencies>
# end <mortgage_calculator dev dependencies>

transformers:
  - polymer:
      entry_points:
        - web/examples/mortgage_calculator/mortgage_calculator.html

# custom <mortgage_calculator transformers>
# end <mortgage_calculator transformers>

