name: ebisu_web_ui
version: 0.0.1
author: Daniel Davidson <dbdavidson@yahoo.com>
dependencies:

# custom <ebisu_web_ui dependencies>

  quiver: ">=0.18.0<0.19.0"

  ebisu: "^0.1.0"

# end <ebisu_web_ui dependencies>

dev_dependencies:
  yaml: "any"
  unittest: ">=0.11.0 < 0.12.0"
  browser: "any"
  hop: "any"
  hop_docgen: "any"

# custom <ebisu_web_ui dev dependencies>

environment:
  sdk: ">=1.8.0 <2.0.0"

# end <ebisu_web_ui dev dependencies>

dependency_overrides:
# custom <ebisu_web_ui dependency overrides>
# end <ebisu_web_ui dependency overrides>

transformers:

# custom <ebisu_web_ui transformers>
# end <ebisu_web_ui transformers>

