name: ebisu_web_ui
version: 0.0.1
author: Daniel Davidson <dbdavidson@yahoo.com>
dependencies:
  pathos:  "any"
  ebisu:
      git: 
        url: git://github.com/patefacio/ebisu
        ref: HEAD

# custom <ebisu_web_ui dependencies>
# end <ebisu_web_ui dependencies>

