name: ebisu_web_ui
version: 0.0.1
author: Daniel Davidson <dbdavidson@yahoo.com>
dependencies:
  ebisu:
      path: /Users/dbdavidson/dev/open_source/ebisu

# custom <ebisu_web_ui dependencies>

  quiver: ">=0.18.0<0.19.0"
  ebisu:
    path: /Users/dbdavidson/dev/open_source/ebisu/

# end <ebisu_web_ui dependencies>

dev_dependencies:
  unittest: ">=0.11.0"
  browser: "any"
  hop: ">=0.31.0"
  hop_docgen: ">=0.1.0 <0.2.0"

# custom <ebisu_web_ui dev dependencies>
# end <ebisu_web_ui dev dependencies>

transformers:

# custom <ebisu_web_ui transformers>
# end <ebisu_web_ui transformers>

