name: ebisu_web_ui
version: 0.0.1
author: Daniel Davidson <dbdavidson@yahoo.com>
dependencies:

# custom <ebisu_web_ui dependencies>

  quiver: ">=0.18.0<0.19.0"

  ebisu:
    git: git://github.com/patefacio/ebisu

# end <ebisu_web_ui dependencies>

dev_dependencies:
  unittest: ">=0.9.0 < 0.10.0"
  browser: "any"
  hop: "any"
  hop_docgen: "any"

# custom <ebisu_web_ui dev dependencies>
# end <ebisu_web_ui dev dependencies>

transformers:

# custom <ebisu_web_ui transformers>
# end <ebisu_web_ui transformers>

